In [ ]:
from nba_api.stats.endpoints import leaguegamefinder
gamefinder = leaguegamefinder.LeagueGameFinder(date_from_nullable='01/01/2024', )

In [57]:
len(gamefinder.get_data_frames())

1

In [ ]:
games = gamefinder.get_data_frames()[0]

In [60]:
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22023,1612709913,BHM,Birmingham Squadron,2022300175,2024-01-24,BHM @ WIS,L,240,107,...,0.700,7,25,32,22,10,6,7,17,-12.6
1,22023,1612709910,IMA,Indiana Mad Ants,2022300171,2024-01-24,IMA vs. CCG,W,247,110,...,0.889,15,26,41,31,8,12,15,22,0.0
2,22023,1610612765,DET,Detroit Pistons,0022300619,2024-01-24,DET vs. CHA,W,240,113,...,0.600,5,39,44,26,4,0,11,17,7.0
3,22023,1610612756,PHX,Phoenix Suns,0022300625,2024-01-24,PHX @ DAL,W,241,132,...,0.727,11,38,49,30,10,4,15,20,23.0
4,22023,1612709917,GRG,Grand Rapids Gold,2022300169,2024-01-24,GRG @ RAP,W,240,115,...,0.952,6,41,47,28,14,8,19,14,4.2

In [61]:
games.iloc[3]

SEASON_ID                   22023
TEAM_ID                1610612756
TEAM_ABBREVIATION             PHX
TEAM_NAME            Phoenix Suns
GAME_ID                0022300625
GAME_DATE              2024-01-24
MATCHUP                 PHX @ DAL
WL                              W
MIN                           241
PTS                           132
FGM                            51
FGA                            85
FG_PCT                        0.6
FG3M                           14
FG3A                           34
FG3_PCT                     0.412
FTM                            16
FTA                            22
FT_PCT                      0.727
OREB                           11
DREB                           38
REB                            49
AST                            30
STL                            10
BLK                             4
TOV                            15
PF                             20
PLUS_MINUS                   23.0
Name: 3, dtype: object

Work with boxscores

In [58]:
from nba_api.stats.static import teams

nba_teams = teams.get_teams()
nba_teams[0:3]

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Georgia',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970}]

In [59]:
nba_ids = [team['id'] for team in nba_teams]
nba_games_dataframe = games[games.TEAM_ID.isin(nba_ids)]
nba_games = nba_games_dataframe.GAME_ID.unique()
nba_games[0:5]

array(['0022300619', '0022300625', '0022300626', '0022300620',
       '0022300622'], dtype=object)

In [51]:
from nba_api.stats.endpoints import boxscoretraditionalv2
game = nba_games[0]
bx = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id=game).get_data_frames()[0]

In [55]:
bx.columns

Index(['GAME_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID',
       'PLAYER_NAME', 'NICKNAME', 'START_POSITION', 'COMMENT', 'MIN', 'FGM',
       'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
       'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PF', 'PTS',
       'PLUS_MINUS'],
      dtype='object')

In [56]:
bx.iloc[0]

GAME_ID                0022300619
TEAM_ID                1610612766
TEAM_ABBREVIATION             CHA
TEAM_CITY               Charlotte
PLAYER_ID                 1628998
PLAYER_NAME           Cody Martin
NICKNAME                     Cody
START_POSITION                  F
COMMENT
MIN                  24.000000:49
FGM                           1.0
FGA                           4.0
FG_PCT                       0.25
FG3M                          0.0
FG3A                          2.0
FG3_PCT                       0.0
FTM                           3.0
FTA                           4.0
FT_PCT                       0.75
OREB                          1.0
DREB                          2.0
REB                           3.0
AST                           3.0
STL                           1.0
BLK                           0.0
TO                            0.0
PF                            2.0
PTS                           5.0
PLUS_MINUS                   -5.0
Name: 0, dtype: object

Go back to league finder, to work with dates

In [5]:
from nba_api.stats.endpoints import leaguegamefinder
gamefinder = leaguegamefinder.LeagueGameFinder(date_from_nullable='01/17/2024', date_to_nullable='01/23/2024', )
gamefinder.get_data_frames()[0].head()
# Notice the date-format adopted by the API !!

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22023,1610612746,LAC,LA Clippers,0022300618,2024-01-23,LAC vs. LAL,W,240,127,...,0.750,6,30,36,33,8,5,14,17,11.0
1,22023,1612709910,IMA,Indiana Mad Ants,2022300164,2024-01-23,IMA vs. CCG,W,241,122,...,0.643,14,40,54,27,11,8,17,18,10.4
2,22023,1612709902,SCW,Santa Cruz Warriors,2022300167,2024-01-23,SCW @ SLC,W,241,126,...,0.500,12,28,40,35,7,1,6,13,15.8
3,22023,1610612751,BKN,Brooklyn Nets,0022300615,2024-01-23,BKN vs. NYK,L,240,103,...,0.800,13,27,40,29,7,5,13,19,-5.0
4,22023,1612709921,LIN,Long Island Nets,2022300165,2024-01-23,LIN vs. MCC,L,240,110,...,0.846,9,33,42,31,5,8,19,19,1.2